=== Ixf2/XSD-XML---Tabla-Peri-dica/elements.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.w3schools.com"
    xmlns="https://www.w3schools.com"
    elementFormDefault="qualified">

    <xs:element name="atoms">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="atom" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="atom">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"></xs:element>
                <xs:element ref="symbol"></xs:element>
                <xs:element ref="atoms_characteristics"></xs:element>
                <xs:element name="discoverer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="discoverer_name" type="nameType"></xs:element>
                            <xs:element name="discoverer_surname1" type="nameType"></xs:element>
                            <xs:element name="discoverer_surname2" type="nameType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bolling_point">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:decimal">
                                <!--use="optional"
                                para dar opcionar el atributo-->
                                <xs:attribute name="unidades" type="unidType" default="centigrados" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="density" type="xs:int" minOccurs="0"></xs:element>
                <xs:element ref="origin"></xs:element>


            </xs:sequence>
            <xs:attribute name="state" type="StateType"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="StateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="solid"></xs:enumeration>
            <xs:enumeration value="liquid"></xs:enumeration>
            <xs:enumeration value="gas"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-ZÁÉÍÓÚÑ][a-záéíóúñ]*" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="symbol">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]{1,3}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="atoms_characteristics">
        <xs:complexType>
            <xs:all> <!--All
                hace que todo lo que haya dentro aunque esté diferente orden lo detecte-->
                <xs:element name="atom_weight" type="xs:decimal"></xs:element>
                <xs:element name="atom_number" type="xs:positiveInteger"></xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]*" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="unidType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="centigrados" />
            <xs:enumeration value="kelvin" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="origin">
        <xs:complexType>
            <xs:choice> <!-- choise o bien es uno u otro-->
                <xs:element name="terrestial">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="seenContinents"></xs:group>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="extraterrestial"></xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
<xs:group name="seenContinents">
    <xs:sequence>
        <xs:element name="terrestrial"></xs:element>
        <xs:element name="extraterrestrial"></xs:element>
    </xs:sequence>
</xs:group>

</xs:schema>

=== Ixf2/XSD-XML---Tabla-Peri-dica/elements.xml
<?xml version="1.0" encoding="UTF-8"?>  
<!-- <!DOCTYPE root-element SYSTEM "file.dtd"> -->

<atoms xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com elements.xsd">
    <atom state="liquid">
        <name>Alfalfa</name>
        <symbol>O</symbol>
        <atoms_characteristics>
            <atom_weight>34</atom_weight>
            <atom_number>1</atom_number>
        </atoms_characteristics>
        <discoverer>
            <name_discoverer>Julian</name_discoverer>
            <surname1_discoverer>Rodriguez</surname1_discoverer>
            <surname2_discoverer>Garcia</surname2_discoverer>
        </discoverer>

        <bolling_point unidades="kelvin">423</bolling_point>
        <density>34</density>
        <origin>
            <terrestrial></terrestrial>
            <extraterrestrial></extraterrestrial>
        </origin>
    </atom>
</atoms>
